name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Check types
        run: npm run check:types
      - name: Lint
        run: npm run check:code:all
      - name: Lint formatting
        run: npm run check:formatting:all
      - name: Test
        run: npm run test
